backend:
  name: git-gateway
  branch: main # Assurez-vous que c'est bien votre branche par défaut

# Cette ligne est maintenant obligatoire
media_library: "cloudinary" 

# Ces lignes sont nécessaires pour que Decap sache où enregistrer les images
media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: pages
    label: Pages
    files:
      - file: "content/springbok.json"
        label: "Page Springbok"
        name: "springbok"
        fields:
          - { label: "Titre (H1)", name: "title", widget: "string" }
          - { label: "Intro (Markdown)", name: "intro_md", widget: "markdown" }
          - { label: "Image héros (desktop)", name: "hero_desktop", widget: "image" }
          - { label: "Image héros (mobile)",  name: "hero_mobile",  widget: "image" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Titre section opérations", name: "ops_title", widget: "string" }
          - { label: "Intro section opérations (Markdown)", name: "ops_intro_md", widget: "markdown", required: false }
          - label: "Opérations"
            name: "operations"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }

      - file: "content/impala.json"
        label: "Page Impala"
        name: "impala"
        fields:
          - { label: "Titre (H1)", name: "title", widget: "string" }
          - { label: "Intro (Markdown)", name: "intro_md", widget: "markdown" }
          - { label: "Image héros (desktop)", name: "hero_desktop", widget: "image" }
          - { label: "Image héros (mobile)",  name: "hero_mobile",  widget: "image" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Titre section opérations", name: "ops_title", widget: "string" }
          - label: "Opérations"
            name: "operations"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
